"""Generate report-ready ablation tables from all completed experiment runs."""

import argparse
import csv
import json
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

import yaml


def _load_run(run_dir: Path) -> dict | None:
    metrics_path = run_dir / "metrics.json"
    config_path = run_dir / "config.yaml"
    if not metrics_path.exists() or not config_path.exists():
        return None

    with open(metrics_path) as f:
        metrics = json.load(f)
    with open(config_path) as f:
        config = yaml.safe_load(f)

    method = config.get("method", {})
    training = config.get("training", {})

    backbone_names: list[str] = method.get("backbone_names", [])
    fusion_type: str = method.get("fusion_type", "none")
    unfreeze_blocks: int = int(training.get("unfreeze_blocks", 0))
    mode = "frozen" if unfreeze_blocks == 0 else f"finetune-{unfreeze_blocks}blk"
    fold: int = int(metrics.get("fold", 0))

    test = metrics.get("test", {})
    accuracy = test.get("accuracy")
    macro_f1 = test.get("macro_f1")
    macro_precision = test.get("macro_precision")
    macro_recall = test.get("macro_recall")

    # Epoch count from history
    history = metrics.get("history", [])
    stop_epoch = history[-1]["epoch"] if history else None

    return {
        "experiment_id": run_dir.name,
        "backbones": "+".join(b[0].upper() for b in backbone_names),
        "backbone_names": ", ".join(backbone_names),
        "fusion_type": fusion_type,
        "mode": mode,
        "unfreeze_blocks": unfreeze_blocks,
        "fold": fold,
        "accuracy": accuracy,
        "macro_f1": macro_f1,
        "macro_precision": macro_precision,
        "macro_recall": macro_recall,
        "stop_epoch": stop_epoch,
    }


def _fmt(val, decimals: int = 4) -> str:
    if val is None:
        return "—"
    return f"{val:.{decimals}f}"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate report-ready ablation tables.")
    parser.add_argument("--runs-dir", default="results/runs", help="Directory containing run subdirectories")
    parser.add_argument("--output-dir", default="results/tables", help="Output directory for tables")
    args = parser.parse_args()

    runs_dir = _ROOT / args.runs_dir
    output_dir = _ROOT / args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    rows = []
    missing = []
    for run_dir in sorted(runs_dir.iterdir()):
        if not run_dir.is_dir() or run_dir.name.startswith("."):
            continue
        row = _load_run(run_dir)
        if row is None:
            missing.append(run_dir.name)
        else:
            rows.append(row)

    if missing:
        print(f"Warning: missing metrics.json or config.yaml in: {missing}")

    if not rows:
        print("No completed runs found.")
        return

    rows.sort(key=lambda r: r["experiment_id"])

    # --- CSV ---
    csv_path = output_dir / "ablation_table.csv"
    fieldnames = [
        "experiment_id", "backbone_names", "fusion_type", "mode", "fold",
        "accuracy", "macro_f1", "macro_precision", "macro_recall", "stop_epoch",
    ]
    with open(csv_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)

    # --- Markdown ---
    md_path = output_dir / "ablation_table.md"
    header = (
        "| Experiment | Backbones | Fusion | Mode | Fold | Acc | Macro F1 | "
        "Macro P | Macro R | Stop ep |\n"
    )
    sep = "|---|---|---|---|---:|---:|---:|---:|---:|---:|\n"
    lines = [
        "# Ablation Table\n\n",
        "_Auto-generated by `scripts/generate_report_tables.py`. "
        "All numbers from `results/runs/{id}/metrics.json`._\n\n",
        header,
        sep,
    ]
    for r in rows:
        line = (
            f"| `{r['experiment_id']}` "
            f"| {r['backbone_names']} "
            f"| {r['fusion_type']} "
            f"| {r['mode']} "
            f"| {r['fold']} "
            f"| {_fmt(r['accuracy'])} "
            f"| {_fmt(r['macro_f1'])} "
            f"| {_fmt(r['macro_precision'])} "
            f"| {_fmt(r['macro_recall'])} "
            f"| {r['stop_epoch'] if r['stop_epoch'] is not None else '—'} |\n"
        )
        lines.append(line)

    with open(md_path, "w") as f:
        f.writelines(lines)

    print(f"Wrote {len(rows)} rows -> {csv_path}")
    print(f"Wrote {len(rows)} rows -> {md_path}")


if __name__ == "__main__":
    main()
